baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Rigonkmalk attic'
theme = 'hugo-blog-awesome'

[params.author]
avatar = "avatar.png"
intro = "Bienvenue sur mon blog"
name = "Paul ( Rigonkmalk ) Azema"
description = "C'est un blog un peu brouillon qui aura pour objectif de comprendre Github Actions et le d√©ploiement avec Hugo"

[module]
[[module.imports]]
    path = 'github.com/hugomods/images'